### ISSUE TITLE
Implementation of QR Code.

### ISSUE THREAD

**Issue by shirshak55** [NadeemShakya/itmeetapp2019#6]
First off all whenever user register he/she will see qr code.

In QR code i have placed email address.

Now you will need to make QR code scanner which scans those QR code extract email address from it

and send request to here in this format
http://itmeet.test/api/v1/verify/shirshak.55@gmail.com

If the user exist it will say user exists and if not it will say exists false.

Let me know if you have any query.

**Comment by NadeemShakya** [comment]
I think this is to be dealt with by the IT MEET v.8.0 Management Team. Their management app should have this feature in it.
